spring:
  datasource:
    url: jdbc:mysql://localhost:3306/chat_app
    username: chat_app_user
    password: chat_app_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  level:
    org.springframework.web.socket: DEBUG
    org.springframework.messaging: DEBUG
jwt:
  secret: L9n1xG6WZf2BL1q2A93FZ1yA8d1zKbnWl3P+xtFlSlM=
  expiration: 86400000

server:
  port: 8080
